paths:
  /user/signin:
    post:
      tags:
        - User
      summary: 회원가입
      parameters:
        - name: signIn
          in: body
          required: true
          schema:
            properties:
              name:
                type: string
                description: 유저 이름
                example: swagger
              nickname:
                type: string
                description: 닉네임
                example: nickname
              gender:
                type: string
                description: 유저 성별
                example: M
              age:
                type: integer
                description: 유저 나이
                example: 22
              address:
                type: string
                description: 주소
                example: swagger Test address
              spec_address:
                type: string
                description: 상세 주소
                example: swagger Test specAddr
              email:
                type: string
                description: 유저 이메일
                example: swaggerTest@mail.com
              phone_number:
                type: string
                description: 전화 번호
                example: 010-0000-0000
              prefer:
                type: array
                description: 선호 카테고리 번호
                example: [1, 3, 5]
      responses:
        "200":
          description: 회원 가입 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: { "email": "swaggerTest@mail.com", "name": "swagger", "preferCategory": ["한식", "일식"] }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
  /user/doMission:
    post:
      tags:
        - User-Mission
      summary: 미션 도전
      parameters:
        - name: doMission
          in: body
          required: true
          schema:
            properties:
              member_id:
                type: integer
                description: 유저 번호
                example: 1
              mission_id:
                type: integer
                description: 미션 번호
                example: 1
              status:
                type: string
                description: 미션 도전 상태
                example: progress
      responses:
        "200":
          description: 미션 도전 시도 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: { "member_id": 1, "mission_id": 1, "status": "progress" }

        "400":
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        "500":
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.
